# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_SPRINT_rcpp_hello_world`)
}

#' Compute the testing quantities without covariates
#' @param yin Working vector
#' @param Pyin The vector P*y
#' @param cov_matin Kernel matrix to be tested
#' @param Din Weight for each gene
#' @param tauin Initial value for variance component
#' 
#' @return A list
#' 
#' 
#' @export
NULL

#' Compute the testing quantities with covariates
#' @param yin Working vector
#' @param Pyin The vector P*y
#' @param Xin Covariate matrix, including the intercept
#' @param cov_matin Kernel matrix to be tested
#' @param Din Weight for each gene
#' @param tauin Initial value for variance component
#' 
#' @return A list
#' 
#' 
#' @export
NULL

#' Variance component estimation with covariates using Average Information algorithm
#' @param Yin Working vector
#' @param Xin Covariate matrix
#' @param Din Weight for each gene
#' @param tauin Initial value for variance component
#' @param fixtauin Variance component to be optimized
#' @param tolin Tolerance
#' 
#' @return A list
#' 
#' @export
CovariatesAI <- function(Yin, Xin, Din, tauin, fixtauin, tolin) {
    .Call(`_SPRINT_CovariatesAI`, Yin, Xin, Din, tauin, fixtauin, tolin)
}

#' Variance component estimation without covariates using Average Information algorithm
#' @param Yin Working vector
#' @param Xin Covariate matrix
#' @param Din Weight for each gene
#' @param tauin Initial value for variance component
#' @param fixtauin Variance component to be optimized
#' @param tolin Tolerance
#' 
#' @return A list
#' 
#' 
#' @export
noCovariatesAI <- function(Yin, Xin, Din, tauin, fixtauin, tolin) {
    .Call(`_SPRINT_noCovariatesAI`, Yin, Xin, Din, tauin, fixtauin, tolin)
}

ComputeTestQuantRcpp_nocov <- function(yin, Pyin, cov_matin, Din, tauin) {
    .Call(`_SPRINT_ComputeTestQuantRcpp_nocov`, yin, Pyin, cov_matin, Din, tauin)
}

ComputeTestQuantRcpp_cov <- function(yin, Pyin, Xin, cov_matin, Din, tauin) {
    .Call(`_SPRINT_ComputeTestQuantRcpp_cov`, yin, Pyin, Xin, cov_matin, Din, tauin)
}

